[platformio]
default_envs = 
    sp530e

[env:sp530e]
extends = env:esp32c3dev
build_flags = ${env:esp32c3dev.build_flags}
    -D BTNPIN=8
    -D ARDUINO_USB_CDC_ON_BOOT=0
    ; -D WLED_RELEASE_NAME=\"SP530E\"
    ; -D WLED_REPO=\"mik-laj/wled-custom-builds\"
build_unflags = -D WLED_RELEASE_NAME -D ARDUINO_USB_CDC_ON_BOOT
