name: WLED compile

on:
  workflow_dispatch:
    inputs:
      wled_version:
        description: 'WLED Version (e.g. 16.0.0)'
        required: true
        default: '16.0.0'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Install PlatformIO
      run: |
        make install-tools

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: Prepare environment
      env:
        WLED_VERSION: ${{ inputs.wled_version }}
      run: |
        make prepare WLED_VERSION=16.0.0
        jq --arg version "$WLED_VERSION" '.version = $version' wled-src/package.json > temp.json && mv temp.json wled-src/package.json

    - name: Prepare Binary
      run: make build

    - name: Create Release
      uses: softprops/action-gh-release@v3
      with:
        tag_name: v${{ inputs.wled_version }}
        name: WLED ${{ inputs.wled_version }} for SP530E

        body: |
          ### Custom Build Details
          - **Version:** ${{ inputs.wled_version }}
          - **Chip:** ESP32-C3
          - **USB CDC:** 0

        files: build_output/*.bin
        fail_on_unmatched_files: true
